spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_tracker
    username: tonmoyjdbc
    password: tonmoy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
